### ISSUE TITLE
request.requestSerializerType == TFRequestSerializerTypeJSON

### ISSUE THREAD

**Issue by ghost** [TimeFaceCoder/TFNetwork#1]
TFNetworkAgent.m [LINE 81] 
else if (request.requestSerializerType == TFRequestSerializerTypeJSON) {
        _manager.requestSerializer = [AFHTTPRequestSerializer serializer];

是不是应该是：_manager.requestSerializer = [AFJSONRequestSerializer serializer];

**Comment by melvin7** [comment]
这块是请求结构体格式。在我们看来这块不需要使用json request
